--- 
http_interactions: 
- request: 
    method: get
    uri: http://api.themoviedb.org/3/configuration?api_key=TMDB_API_KEY
    body: 
      encoding: US-ASCII
      string: ""
    headers: {}

  response: 
    status: 
      code: 200
      message: 
    headers: 
      age: 
      - "3501"
      cache-control: 
      - public, max-age=36000
      content-type: 
      - application/json;charset=utf-8
      date: 
      - Wed, 13 Jun 2012 20:47:33 GMT
      server: 
      - nginx
      status: 
      - 200 OK
      via: 
      - 1.1 varnish
      x-cache: 
      - HIT
      x-frame-options: 
      - sameorigin
      x-varnish: 
      - 994735795 994125650
      x-varnish-sid: 
      - tm-v-p-1200
      x-xss-protection: 
      - 1; mode=block
      content-length: 
      - "284"
      connection: 
      - Close
    body: 
      encoding: US-ASCII
      string: "{\"images\":{\"base_url\":\"http://cf2.imgobject.com/t/p/\",\"poster_sizes\":[\"w92\",\"w154\",\"w185\",\"w342\",\"w500\",\"original\"],\"backdrop_sizes\":[\"w300\",\"w780\",\"w1280\",\"original\"],\"profile_sizes\":[\"w45\",\"w185\",\"h632\",\"original\"],\"logo_sizes\":[\"w45\",\"w92\",\"w154\",\"w185\",\"w300\",\"w500\",\"original\"]}}"
    http_version: 
  recorded_at: Wed, 13 Jun 2012 20:47:33 GMT
recorded_with: VCR 2.2.0
